# Generated by Django 4.0.1 on 2022-01-26 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_range_start', models.TimeField(blank=True, null=True)),
                ('call_range_end', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_far_east', models.BooleanField(default=False)),
                ('call_range_start', models.TimeField(blank=True, null=True)),
                ('call_range_end', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('product_managers', models.ManyToManyField(related_name='weeks', to='core.ProductManager')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_call_at', models.TimeField()),
                ('members', models.ManyToManyField(to='core.Student')),
                ('product_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='core.productmanager')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='core.week')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productmanager',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
