# Generated by Django 4.0.1 on 2022-01-27 09:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_productmanager_project_student_user_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField(blank=True, null=True)),
                ('end', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Временной интервал',
                'verbose_name_plural': 'Временные интервал',
                'unique_together': {('start', 'end')},
            },
        ),
        migrations.CreateModel(
            name='StudentProjectPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_any_time', models.BooleanField(help_text='отметить, если устраивает любой из интервалов', verbose_name='в любое время?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата/время создания')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='core.project', verbose_name='проект')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects_preferences', to='core.student', verbose_name='студент')),
                ('time_slots', models.ManyToManyField(blank=True, related_name='time_slots', to='core.TimeSlot', verbose_name='временные интервалы')),
            ],
            options={
                'verbose_name': 'Предпочтения',
                'verbose_name_plural': 'Предпочтения',
                'unique_together': {('student', 'project')},
            },
        ),
    ]
