# Generated by Django 4.0.1 on 2022-01-27 10:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_student_user_timeslot_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'verbose_name': 'Временной интервал', 'verbose_name_plural': 'Временные интервалы'},
        ),
        migrations.RemoveField(
            model_name='student',
            name='call_range_end',
        ),
        migrations.RemoveField(
            model_name='student',
            name='call_range_start',
        ),
        migrations.AddField(
            model_name='student',
            name='discord_username',
            field=models.CharField(default='', max_length=32, verbose_name='пользовательское имя в Discord'),
        ),
        migrations.AddField(
            model_name='student',
            name='joined_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='дата создания записи'),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='имя/ник'),
        ),
        migrations.AddField(
            model_name='student',
            name='tg_username',
            field=models.CharField(default='', max_length=32, verbose_name='пользовательское имя в Telegram'),
        ),
        migrations.AddField(
            model_name='studentprojectpreferences',
            name='is_any_week',
            field=models.BooleanField(default=False, help_text='отметить, если устраивает любая неделя', verbose_name='на любой неделе?'),
        ),
        migrations.AddField(
            model_name='studentprojectpreferences',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_weeks', to='core.week', verbose_name='неделя'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_far_east',
            field=models.BooleanField(default=False, verbose_name='с Дальнего Востока?'),
        ),
        migrations.AlterField(
            model_name='studentprojectpreferences',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='дата/время создания'),
        ),
        migrations.AlterField(
            model_name='studentprojectpreferences',
            name='is_any_time',
            field=models.BooleanField(default=False, help_text='отметить, если устраивает любой из интервалов', verbose_name='в любое время?'),
        ),
    ]
