# Generated by Django 4.0.1 on 2022-01-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_timeslot_options_remove_student_call_range_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='tg_chat_id',
            field=models.CharField(default='', max_length=10, verbose_name='идентификатор пользователя в Telegram'),
        ),
    ]
