# Generated by Django 4.0.1 on 2022-01-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_student_tg_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(default='', max_length=32, verbose_name='уровень'),
        ),
    ]
