# Generated by Django 4.0.1 on 2022-01-30 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_student_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmanager',
            name='user',
        ),
    ]
