# Generated by Django 4.0.1 on 2022-01-29 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_student_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmanager',
            name='name',
            field=models.CharField(default=1, max_length=20, verbose_name='имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeslot',
            name='product_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.productmanager', verbose_name='продукт-менеджер'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.student', verbose_name='студент'),
        ),
        migrations.AlterField(
            model_name='productmanager',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end',
            field=models.TimeField(blank=True, null=True, verbose_name='конец созвона'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start',
            field=models.TimeField(blank=True, null=True, verbose_name='начало созвона'),
        ),
    ]
