# Generated by Django 4.0.1 on 2022-01-29 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_productmanager_name_timeslot_product_manager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmanager',
            name='call_range_end',
        ),
        migrations.RemoveField(
            model_name='productmanager',
            name='call_range_start',
        ),
    ]
