# Generated by Django 4.0.1 on 2022-01-29 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_productmanager_call_range_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='product_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pm_time_slots', to='core.productmanager', verbose_name='продукт-менеджер'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_time_slots', to='core.student', verbose_name='студент'),
        ),
    ]
